// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c387d8de-6495-4968-8671-e82408b56e42",
    "aws_cognito_region": "us-east-1",
    "aws_mobile_analytics_app_id": "e2ed84eb705347838766a8468d002f9c",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
